post:
  tags:
    - Services
  summary: Create a Service
  description: Creates a brand new service
  operationId: create-service
  security:
    - jwt: []
  responses:
    '201':
      description: Created
      content:
        application/json:
          schema:
            $ref: ../components/responses/201.yaml
    '403':
      description: Not permitted to perform operation
      content:
        application/json:
          schema:
            $ref: ../components/responses/403.yaml
    '422':
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            $ref: ../components/responses/422.yaml
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/service_payload.yaml
    required: true
