openapi: 3.0.2
info:
  version: 0.1.0
  title: MoJ Online Form Builder Metadata API Docs
  contact:
    email: form-builder-developers@digital.justice.gov.uk
  x-logo:
    url: 'https://raw.githubusercontent.com/ministryofjustice/fb-editor-console-electron/63a0d9a4cda23f361a1d52aa7af9400db29621ee/assets/images/govuk-crown.png'
  description: >
    # Introduction

    >
      This is the Form Builder Metadata API documentation.

    >
      The application is responsible for storing and serving metadata versions for all the services
    created by the MoJ Online Form Builder tool.

    >
      The code repository [can be found here](https://github.com/ministryofjustice/fb-metadata-api).

    >
      In order to interact with the API each request must have a JWT bearer token in the Authorizaion
    header signed by a private key.
paths:
  /services:
    $ref: 'paths/services.yaml'
  /services/{service_id}/versions:
    $ref: 'paths/services@{service_id}@versions.yaml'
  /services/{service_id}/versions/latest:
    $ref: 'paths/services@{service_id}@versions@latest.yaml'
  /services/{service_id}/versions/{version_id}:
    $ref: 'paths/services@{service_id}@versions@{version_id}.yaml'
  /services/users/{user_id}:
    $ref: 'paths/services@users@{user_id}.yaml'
components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - jwt: []
